apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "psql-query-exporter.fullname" . }}
  labels:
    {{- include "psql-query-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
