apiVersion: v1
kind: Service
metadata:
  name: {{ include "psql-query-exporter.fullname" . }}
  labels:
    {{- include "psql-query-exporter.labels" . | nindent 4 }}
  annotations:
   prometheus.io/port: {{ .Values.service.port | quote }}
   prometheus.io/scheme: http
   prometheus.io/path: /metrics
   prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "psql-query-exporter.selectorLabels" . | nindent 4 }}
