name: Security audit
on:
  schedule:
    - cron: "17 5 * * 5"
  push:
    branches:
      - main
      - fix/update-to-get-rid-of-outdated-actions
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
