name: Security audit
on:
  schedule:
    - cron: "17 5 * * 5"
  pull_request:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - deny.toml
  push:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - deny.toml

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
