on:
  pull_request:
  schedule:
    - cron: "17 5 * * 5"

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build

      - name: Generate TLS certificates
        run: |
          tests/scripts/create-test-certificates.sh
          sudo chmod 400 tests/tls/server.key
          sudo chmown 70 tests/tls/server.key

      - name: Test
        env:
          RUST_LOG: debug
        run: cargo test

  docker-test:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Test image build
        run: docker build .
