name: Continuous integration
on:
  pull_request:
  schedule:
    - cron: "17 5 * * 5"
permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Build
        run: cargo build

      - name: Generate TLS certificates
        run: |
          tests/scripts/create-test-certificates.sh
          sudo chmod 400 tests/tls/*.key
          sudo chown 70 tests/tls/server.key

      - name: Test with latest PostgreSQL version (17)
        run: cargo test

      - name: Test with minimal supported PostgreSQL version (13)
        env:
          PG_VERSION: "13"
        run: cargo test

      - name: Test with still used PostgreSQL version (11)
        env:
          PG_VERSION: "11"
        run: cargo test

  docker-test:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Test image build
        run: docker build .
