name: Code coverage report
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: nightly
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Setup coverage tool
        run: |
          mkdir -p grcov
          curl -sL https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | (cd grcov ; tar jxf -)

      - name: Generate TLS certificates
        run: |
          tests/scripts/create-test-certificates.sh
          sudo chmod 400 tests/tls/server.key
          sudo chmown 70 tests/tls/server.key

      - name: Test
        env:
          CI: true
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: psql-query-exporter-%p-%m.profraw
          DISABLE_CONTAINER_DESTRUCTORS: "true"
        run: cargo test --all -- --include-ignored --nocapture

      - name: Generate coverage
        run: |
          grcov/grcov $(find . -name "psql-query-exporter-*.profraw" -print) \
            --branch \
            --ignore-not-existing \
            --binary-path ./target/debug/ \
            -s src \
            -t lcov \
            --ignore "/*" \
            --excl-line '^\s*\.await\??;?$' --excl-br-line '^\s*\.await\??;?$' \
            -o lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./lcov.info
